version: '3.8'

services:
  fred-ml:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FRED_API_KEY=${FRED_API_KEY}
      - ENVIRONMENT=development
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - redis
    networks:
      - fred-ml-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - fred-ml-network

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: fred_ml
      POSTGRES_USER: fred_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fred-ml-network

volumes:
  redis_data:
  postgres_data:

networks:
  fred-ml-network:
    driver: bridge 