fred:
  api_key: "acf8bbec7efe3b6dfa6ae083e7152314"
  series:
    - GDP
    - UNRATE
    - CPIAUCSL
    - FEDFUNDS
    - DGS10
  start_date: "2010-01-01"
  end_date: "2024-01-01"
  output_dir: "data/processed"
  export_dir: "data/exports"
  schedule: "0 0 1 */3 *"  # First day of every quarter at midnight UTC
logging:
  level: INFO
  file: logs/pipeline.log 